

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("topGO")

## to get citation list
install.packages("devtools")
devtools::install_github("easystats/report")
#library(report)
#library(biomaRt)
#library(blockmodeling)
library(ChAMP)
#library(cluster)
#library(dplyr)
#library(dynamicTreeCut)
#library(factoextra)
#library(flashClust)
#library(ggplot2)
#library(ggpubr)
#library(gtools)
#library(Hmisc)
#library(impute)
#library(lattice)
#library(NbClust)
#library(pheatmap)
#library(plyr)
#library(pvclust)
#library(RColorBrewer)
#library(readr)
#library(rmarkdown)
library(stats)
#library(survival)
#library(topGO)
#library(WGCNA)
cite_packages()

library(report)
library(topGO)
cite_packages()
